## Question 1: 
What's the version of Pandas that you installed?

In [5]:
import pandas as pd
pd.__version__

'2.0.3'

## Question 2: How many columns are in the dataset?
* [x] 10
* [ ] 6560
* [ ] 10989
* [ ] 20640

In [3]:
!wget 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv'

--2023-09-12 06:03:22--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8003::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  2.39MB/s    in 0.6s    

2023-09-12 06:03:23 (2.39 MB/s) - ‘housing.csv’ saved [1423529/1423529]



In [6]:
df = pd.read_csv('housing.csv')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


## Question 3 Which columns in the dataset have missing values?
* [ ] `total_rooms`
* [x] `total_bedrooms`
* [ ] both of the above
* [ ] no empty columns in the dataset

In [8]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## Question 4: How many unique values does the ocean_proximity column have?
* [ ] 3
* [X] 5
* [ ] 7
* [ ] 9

In [10]:
df.ocean_proximity.nunique()

5

## Question 5: What's the average value of the median_house_value for the houses located near the bay?
* [ ] 49433
* [ ] 124805
* [X] 259212
* [ ] 380440

In [13]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [14]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [16]:
df.median_house_value[df.ocean_proximity == 'NEAR BAY'].mean()

259212.31179039303

## Question 6
1. Calculate the average of total_bedrooms column in the dataset.
2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3. Now, calculate the average of total_bedrooms again.
Has it changed?

Hint: take into account only 3 digits after the decimal point.

* [ ] Yes
* [x] No

In [18]:
mean_value = df.total_bedrooms.mean()
mean_value

537.8705525375618

In [19]:
df.total_bedrooms.isnull().sum()

207

In [20]:
df.total_bedrooms.fillna(value=mean_value, inplace=True)

In [21]:
df.total_bedrooms.isnull().sum()

0

In [22]:
df.total_bedrooms.mean()

537.8705525375617

## Question 7
1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

* [ ] -1.4812
* [ ] 0.001
* [x] 5.6992
* [ ] 23.1233

In [26]:
X = df[['housing_median_age', 'total_rooms', 'total_bedrooms']][df.ocean_proximity == 'ISLAND'].to_numpy()

In [27]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [28]:
XT = X.transpose()

In [29]:
XT

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [31]:
import numpy as np
XTX = np.dot(XT, X)

In [32]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [33]:
inverse_XTX = np.linalg.inv(XTX)

In [34]:
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [35]:
y = np.array([950, 1300, 800, 1000, 1300])

In [36]:
w = np.dot(np.dot(inverse_XTX, XT), y)

In [37]:
w

array([23.12330961, -1.48124183,  5.69922946])

In [38]:
w[-1]

5.699229455065586